**Task 1:**

In [1]:
# 1.
# Write a function to compute 5/0 and use try/except to catch the exceptions.

def div(num1, num2):
    try:
        return num1/num2
    except ZeroDivisionError:
        return "Infinity"
    
print(div(500, 20))
print(div(5,0))

25.0
Infinity


In [2]:
# 2.
# Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
# Hint: Subject,Verb and Object should be declared in the program as shown below.
# subjects=["Americans ","Indians"]
# verbs=["play","watch"]
# objects=["Baseball","Cricket"]
# Output should come as below:
# Americans play Baseball.
# Americans play Cricket.
# Americans watch Baseball.
# Americans watch Cricket.
# Indians play Baseball.
# Indians play Cricket.
# Indians watch Baseball.
# Indians watch Cricket.

subjects=['Americans', 'Indians']
verbs=['play', 'watch']
objects=['Baseball', 'Cricket']
for subject in subjects:
    for verb in verbs:
        for object in objects:
            print(subject, verb, object)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


**Task 2:**

In [3]:
# 1.
# Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
# HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

import numpy as np

def atv(x, N, increasing=True):
    if increasing==True:
        return np.column_stack([x**i for i in range(N)])
    else:
        return np.column_stack([x**(N-1-i) for i in range(N)])
    
x = np.array([1, 2, 3])
N=4
print(atv(x, N, increasing=False))
print("")
print(atv(x, N))

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]]

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]]
